feat: unify all release steps in a single pipeline
nearform/initium-cli pull request #113
Opened 2023-09-22 06:55 UTC by LucaLanziani

The previous solution published the npm package before the go binary was built and attached to the release, causing the npm package to fail without error messages.

Adding all steps in a single action will ensure the right order and the npm package will work right after being published

2023-09-25 21:29 UTC, nearform-kenan commented on .github/workflows/release-please.yaml
> +      - uses: actions/checkout@v3
please bump the version to `v4`

2023-09-25 21:31 UTC, nearform-kenan requested changes

2023-09-25 21:31 UTC, nearform-kenan commented on .github/workflows/release-please.yaml
> +      - uses: actions/checkout@v3
please bump the version to `v4`

2023-09-25 21:31 UTC, nearform-kenan commented on .github/workflows/release-please.yaml
> +        uses: goreleaser/goreleaser-action@v4
please bump the version to `v5`

2023-09-25 21:31 UTC, nearform-kenan commented on .github/workflows/release-please.yaml
>        - uses: actions/checkout@v2
latest version is `v4`

2023-09-26 06:41 UTC, zaremba-tomasz commented on .github/workflows/release-please.yaml
> +      - name: fetch tags
What's the point of this step?

2023-09-26 07:59 UTC, zaremba-tomasz approved these changes

2023-09-26 08:16 UTC, nearform-kenan approved these changes

2023-09-26 08:35 UTC, merged